version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Deploy to EC2 instance
          command: |

            ssh-keyscan -H 13.115.3.151 >> ~/.ssh/known_hosts
            ls
            pwd
            # Copy the files to the EC2 instance
            scp -r ./* ubuntu@13.115.3.151:~/app

            # SSH into the instance and run the deploy script
            ssh ubuntu@13.115.3.151 'cd ~/app && ./deploy.sh'
            
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main