version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Deploy to EC2 instance
          command: |

            ssh-keyscan -H ${EC2_INSTANCE_IP} >> ~/.ssh/known_hosts
            ls
            pwd
            # Copy the files to the EC2 instance
            scp -r ./* ubuntu@${EC2_INSTANCE_IP}:~/app

            # SSH into the instance and run the deploy script
            ssh ubuntu@${EC2_INSTANCE_IP} 'cd ~/app && ./deploy.sh'
            
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main