version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Deploy to EC2 instance
          command: |

            ssh-keyscan -H ${EC2_INSTANCE_IP} >> ~/.ssh/known_hosts
            
            # SSH into the instance and run the deploy script
            ssh ubuntu@${EC2_INSTANCE_IP} 'rm -r app && git clone https://github.com/bbhupen/Hostel-Management.git && cd ~/app && chmod +x deploy.sh && ./deploy.sh'
            
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main