version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && \
            sudo apt-get -y install awscli

      - run:
          name: Deploy to EC2 instance
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION

            # Copy the files to the EC2 instance
            scp -r ./dist ubuntu@${EC2_INSTANCE_IP}:~/app

            # SSH into the instance and run the deploy script
            ssh ubuntu@${EC2_INSTANCE_IP} 'cd ~/app && ./deploy.sh'
            
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
